### ISSUE TITLE
The auto-config for handler classes seems not to work (manual config is required)

### ISSUE THREAD

**Issue by Moongazer** [WapplerSystems/messenger#19]
The extension CompilerPass sets a configuration to tag `MessageHandlerInterface` classes with `messenger.message_handler`:
```
$container->registerForAutoconfiguration(MessageHandlerInterface::class)->addTag('messenger.message_handler');
```
But just implementing the interface for a custom handler class seems not be enough, the handler is never called and all messages are rejected. Only if we manually add the handler-class with this tag to our `Services.yaml` the handler is executed:
```
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Vendor\MyExt\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Vendor\MyExt\Messenger\Handler\MyJobHandler:
    tags:
      - name: 'messenger.message_handler'
```
Is this expected behaviour or is here missing something? Strange is, that in BOTH cases (with and without manual configuration), the tag never shows up in the cached DI file `di/DependencyInjectionContainer_4a...2a.php`: after clearing the cache, searching for `messenger.message_handler` return 0 results.
